config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"

  get "/home", to: "pages#home"
  get "/about", to: "pages#about"


  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"
  get '/newboard', to: "boards#new"
  delete '/delete_list/:id', to: "boards#delete_list"
  resources :users, except: [:new]
  resources :boards, except: [:new]
  resources :list, except: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord

    belongs_to :user
    has_many :board_permissions, dependent: :destroy
    has_many :lists, dependent: :destroy

end

app/models/board_permission.rb
class BoardPermission < ApplicationRecord

    belongs_to :board


end

app/models/list.rb
class List < ApplicationRecord

    belongs_to :board
    has_many :tasks, dependent: :destroy

end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :list

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    before_save { self.email = email.downcase }

    has_many :boards, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in, :find_boards

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in
        !!current_user
    end

    def find_boards
        @boards ||= Board.where user_id: session[:user_id] if session[:user_id]
    end

    def require_user
        if !logged_in
            flash[:danger] = "You must be logged in to perform that action."
            redirect_to root_path
        end
    end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

    before_action :set_board, only: [:edit,:update,:show]

    def index
    end

    def show
    end

    def new
        @board = Board.new
    end

    def create
        @board = Board.new(board_params)
        @board.user_id = session[:user_id]
        #create board
        board_created = false
        if(@board.save)
            board_created = true
            flash[:success] = "#{@board.title} was successfully created."
            #redirect_to(board_path(@board)) and return
        else
            flash.now[:warning] = "Cannot create board right now."
            render 'new'
        end
        #create permission
        bm_created = false
        if board_created == true
            bm = BoardPermission.new
            bm.user_id = session[:user_id]
            bm.board_id = @board.id
            bm.permission = 2
            bm.save
            bm_created = true
        end
        #create lists
        if bm_created == true
            lists = []
            if params[:feature] == "on"
                lists.push("feature")
            end
            if params[:development] == "on"
                lists.push("development")
            end
            if params[:testing] == "on"
                lists.push("testing")
            end
            if params[:production] == "on"
                lists.push("production")
            end

            if lists.length > 0
                position = 1
                lists.each do  |list|
                    new_list = List.new
                    new_list.board_id = @board.id
                    new_list.title = list
                    new_list.position = position
                    new_list.save
                    position += 1
                end
            end
            flash[:success] = "Board and its lists successfully created."
            redirect_to board_path(@board) and return
        end
        flash.now[:danger] = "Cannot create board right now."
        render 'new'
    end

    def edit
    end

    def update
        if @board.update(board_params)
            debugger
            flash[:success] = "Board updated successfully."
            redirect_to board_path(@board) and return
        else
            flash.now[:warning] = "Cannot update your board right now."
            render 'edit'
        end
    end

    def destroy
        @board = Board.find(params[:id])
        @board.destroy
        flash[:success] = "Board and its lists have been deleted."
        redirect_to :back and return
    end

    def delete_list
        #redirect_to root_path
    end

    private #--------------------------------------------------------------------

    def board_params
        params.require(:board).permit(:title,:user_id)
    end

    def set_board
        @board = Board.includes(:lists).find(params[:id])
    end

    def board_owner
        if @board.user_id != session[:user_id]
            flash[:info] = "You cannot perform any action on this board."
            redirect_to boards_path and return
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
        redirect_to user_path(current_user) if logged_in
    end

    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in."
            redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information."
            render "new" and return
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have successfully logged out."
        redirect_to root_path
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:edit,:update,:show]
    before_action :require_same_user, only: [:edit,:update,:destroy]
    before_action :require_admin_user, only: [:destroy,:index]

    def index
        @users = User.all
    end

    def new
       @user = User.new 
    end

    def create
        #debugger
        @user = User.new(user_params)
        if(params[:user][:password] != params[:user][:confirm_password])
            @user.errors.add(:password, "Passwords do not match.")
            render "new" and return
        end
        if(@user.save)
            session[:user_id] = @user.id
            flash[:success] = "You have successfully signed up."
            redirect_to user_path(@user) and return
        else
            flash.now[:warning] = "Cannot create your account right now."
            render "new"
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Account updated successfully."
            redirect_to user_path(@user) and return
        else
            flash.now[:warning] = "Cannot update your account right now."
            render 'edit'
        end
    end

    def show
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:success] = "User and all boards created by the user have been deleted."
        redirect_to users_path and return
    end

    private #---------------------------------------------------------------------

    def set_user
        @user = User.includes(:boards).find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username,:email,:password)
    end

    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:info] = "You can only edit your own account."
            redirect_to root_path
        end
    end

    def require_admin_user
        if logged_in and !current_user.admin?
            flash[:danger] = "Only admin users can perform that action."
            redirect_to root_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options={size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.erb
<%= render "shared/errors", obj: @board -%>

<%= form_for(@board, :html => {class: "form"}) do |f| -%>
    <div class="form-group row">
        <%= f.label :board_title, class: "col-sm-2 col-form-label" -%>
        <%= f.text_field :title, class: "col-sm-8 form-control", placeholder: "Enter board title", autofocus: true -%>
    </div>
    <% if @board.new_record? -%>
        <div class="form-group">
            <div class="row offset-2">
                Want some default lists?
            </div>
            <div class="row form-check offset-2 col-sm-4">
                <input type="checkbox" class: "form-check-input" name="feature" />
                <label class="form-check-label">Feature</label>
            </div>
            <div class="row form-check offset-2 col-sm-4">
                <input type="checkbox" class: "form-check-input" name="development" />
                <label class="form-check-label">Development</label>
            </div>
            <div class="row offset-2 form-check col-sm-4">
                <input type="checkbox" class: "form-check-input" name="testing" />
                <label class="form-check-label">Testing</label>
            </div>
            <div class="row offset-2 form-check col-sm-4">
                <input type="checkbox" class: "form-check-input" name="production" />
                <label class="form-check-label">Production</label>
            </div>
        </div>
    <% else-%>
        <div class="form-group">
            <div class="row offset-2">
                Edit lists:
            </div>
            <% @board.lists.each do |list| -%>
                <div class="row">
                    <div class="form-check offset-2 col-sm-4">
                        <input type="text" class="form-control" value="<%= list.title -%>">
                    </div>
                    Position: <select name="<%= list.title -%>_position" class="select">
                                <% for i in 0..@board.lists.length -%>
                                    <option value="<%= i -%>" <% if i == list.position -%> selected<% end -%> ><%= i -%></option>
                                <% end %>
                              </select>
                    <div class="col">
                    <%= link_to "Delete List", {controller: "boards", action: "delete_list", id: list.id}, method: :delete, data: {confirm: "Are you sure you want to delete this list?"}, class:"btn btn-info" -%>
                    </div>
                </div>
            <% end %>
        </div>
    <% end -%>
    <%= f.submit(@board.new_record? ? "Create Board" : "Update Board", class: "offset-2 col-sm-3 btn btn-dark") -%>
<% end -%>

app/views/boards/edit.html.erb
<h1 align="center">Edit your Board:</h1>

<%= render 'form' -%>

app/views/boards/index.html.erb
<%= debug(@boards) -%>
<%= debug(@user) -%>

app/views/boards/new.html.erb
<h1 align="center"> Create a Board </h1>

<%= render 'form' -%>

app/views/boards/show.html.erb
<h2 align="center"><%= @board.title -%></h2>

<div class="row">

    <% @board.lists.each do |list| -%>
        <div class="col">
            <%= list.title -%><br />
            <%= debug(list.tasks) -%>
        </div>
    <% end -%>

</div>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="offset-1 col-10">
        <% flash.each do |name,msg| -%>
            <div class='alert alert-<%= "#{name}" -%>'>
                <a herf="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div,msg,:id => "flash_#{name}" if msg.is_a? (String) -%>
            </div>
        <% end -%>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path -%>">Dc-Trello</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path -%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if logged_in -%>
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Boards
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <% boards = find_boards %>
        <% if boards.length > 0 -%>
          <% boards.each do |board| -%>
            <a class="dropdown-item" href="<%= board_path(board) -%>"><%= board.title -%></a>
          <% end -%>
          <div class="dropdown-divider"></div>
        <% end -%>
          
          <a class="dropdown-item" href="/newboard">Create New Board</a>
        </div>
      </li>
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Your Profile
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= user_path(current_user) -%>">View</a>
          <a class="dropdown-item" href="<%= edit_user_path(current_user) -%>">Edit Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/logout">Logout</a>
        </div>
      </li>
      <% else -%>
        <li class="nav-item">
          <a class="nav-link" href="/signup">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
      <% end -%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DcTrello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/darkly/bootstrap.min.css" rel="stylesheet" integrity="sha384-F7cPHYSdE3FzBKvdxDKyFow9Y28Yq7KGHQOKpOI+rwc8s6jJnp///mpEJAib2EM6" crossorigin="anonymous">
  </head>
  <body>
    <%= render "layouts/navigation" -%>
    <%= render "layouts/messages" -%>
    <div class="container">
      <%= yield %>
    </div>
    <div class="jumbotron">
      <%= debug(params) if Rails.env.development? -%>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
home page

app/views/shared/_errors.html.erb
<% if obj.errors.any? -%>
    <div class="row">
        <div class="card w-100 bg-danger text-center">
            <div class="card-header">Error</div>
                <div class="card-title">
                    <%= pluralize(obj.errors.count, "error") -%>
                    prohibited this from getting saved: 
                </div>
                <div class="card-body">
                    <ul>
                        <% obj.errors.full_messages.each do |message| -%>
                            <li><%= message -%></li>
                        <% end -%>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<% end -%>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user -%>
<%= form_for(@user, :html => {class: "form"}) do |f| %>
    <div class="form-group row">
        <%= f.label :username, class: "col-sm-2 col-form-label" -%>
        <%= f.text_field :username, class: "col-sm-8 form-control", placeholder: "Enter username", autofocus: true -%>
    </div>
    <div class="form-group row">
        <%= f.label :email, class: "col-sm-2 col-form-label" -%>
        <%= f.email_field :email, class: "col-sm-8 form-control", placeholder: "Enter email" -%>
    </div>
    <% if @user.new_record? -%>
    <div class="form-group row">
        <%= f.label :password, class: "col-sm-2 col-form-label" -%>
        <%= f.password_field :password, class: "col-sm-8 form-control", placeholder: "Enter password" -%>
    </div>
    <div class="form-group row">
        <%= f.label :password_again, class: "col-sm-2 col-form-label" -%>
        <%= f.password_field :confirm_password, class: "col-sm-8 form-control", placeholder: "Enter password again" -%>
    </div>
    <% end -%>
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "offset-2 col-sm-3 btn btn-dark" ) -%>
<% end %>

app/views/users/edit.html.erb
<h1 align="center">Edit your Account:</h1>

<%= render 'form' -%>

app/views/users/new.html.erb
<h1 align="center">SignUp</h1>

<%= render 'form' -%>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username -%>'s page</h1>
<div class="row">
    <div align="center" class="col">
        <%= gravatar_for(@user, size: 150) -%>
    </div>
</div>
<h4 align="center"> <%= @user.username -%>'s boards</h4>
<div class="row">
    <div align="center" class="col">
        <% if @user.boards.length > 0 -%>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Board Name</th>
                        <th>Lists</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <% @user.boards.each do |board| -%>
                        <tr>
                            <td><%= board.title -%></td>
                            <td>
                                <% board.lists.each do |list| -%>
                                    <%= list.title -%> | 
                                <% end -%>
                            </td>
                            <td><%= link_to "Show", board_path(board), class: "btn btn-primary" -%>
                                <%= link_to "Edit", edit_board_path(board), class: "btn btn-info" -%>
                                <%= link_to "Delete", board_path(board), method: :delete, data: {confirm: "Are you sure you want to delete this board and it's lists?"}, class: "btn btn-danger" -%>
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                                    Launch demo modal
                                </button>
                            </td>
                        </tr>
                    <% end -%>
                </tbody>
            </table>
        <% end -%>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add List</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/add_list" method="post" class="form-horizontal">
            <div class="form-group row">
                <label class="form-label">Title</label>
                <input type="text" name="title" class="form-control" placeholder="Enter list title">
            </div>
            <label class="form-label">Position:</label>
            <select name="new_list_position" class="select">
                <% for i in 0.. -%>
            </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>